spring:
  h2:
    console: true
    path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLLOSE_ON_EXIT=FALSE
    username: sa
    password:
  kafka:
    bootstrap-severs: localhost:9092
    topic:
      userCreated: USER_CREATED_TOPIC
security:
  basic:
    enabled: false